# Generated by Django 4.2.4 on 2023-08-23 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
